### ISSUE TITLE
[골드2] 17136.색종이 붙이기(3/5)

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Study/algorithm#316]
🔗 문제 링크
https://www.acmicpc.net/problem/17136

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by skdudddl** [comment]
🔗 문제 링크
#391 

🔥 메모리: 20636KB
🔥 시간: 244ms

💡 풀이 사항
📆풀이 일자: 2024.03.05
⏰풀이 시간: 2시간 이상
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형:  DFS, 구현

✍ 풀이 방법

- DFS(재귀)를 이용함
- 열과 행을 정하는 것은 저번에 연구소 강사님 코드로 /, %로 지정함
- 1~5번까지 가능한지 체크하고 완탐으로 돌렸다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#405 

🔥 메모리: 297632KB
🔥 시간: 608ms

💡 풀이 사항
📆풀이 일자: 2024.03.11
⏰풀이 시간: 2시간 이상
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형:  DFS, 구현

✍ 풀이 방법

- 재귀 이용
