### ISSUE TITLE
[골드1] 3954. Brainf**k 인터프리터(3/5)

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Study/algorithm#317]
🔗 문제 링크
https://www.acmicpc.net/problem/3954

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
🔗 문제 링크
#396 

🔥 메모리: 몰라
🔥 시간: 몰라


💡 풀이 사항
📆풀이 일자: 2024.03.07
⏰풀이 시간: 이틀 넘게 풀었어
✨채점 결과: 오답🙅‍♀️🙅‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- 이건 풀라고 만든 문제가 아니다
- 이틀 넘게 고민하다가 다른 사람의 풀이를 봤다
- 똑같이 구현했지만 틀렸다
- 이유를 모르겠다
- 알겠는 사람은 내 코드를 한번 봐바라
