### ISSUE TITLE
[Level2] 택배상자

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Study/algorithm#388]
🔗 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/131704

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ramrami-S** [comment]
🔗 문제 링크
#395

🔥 메모리: 
🔥 시간: 


💡 풀이 사항
📆풀이 일자: 2024.03.06
⏰풀이 시간: 18분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
🔗 문제 링크
#404 

🔥 메모리: 
🔥 시간: 


💡 풀이 사항
📆풀이 일자: 2024.03.06
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- Stack을 사용해서 미리 담고 필요한 택배가 있으면 추가했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
https://github.com/Hanbat-Study/algorithm/pull/433

🔥 메모리:
🔥 시간:

💡 풀이 사항
📆풀이 일자: 2024.03.18
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 지금 내 번호보다 작거나 같으면 먼저 스택에 넣어줬다
- 그 후 스택이 안 비어있고 peek가 지금의 번호와 같다면 pop과 answer + 1
