### ISSUE TITLE
[Level2] 스킬트리

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Study/algorithm#389]
🔗 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/49993

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Study/algorithm/pull/397


💡 풀이 사항
📆풀이 일자: 2024.03.07
⏰풀이 시간: 1시간
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
각 알파벳의 등급을 저장해, 등급 이상인지 확인해주면서 찾는다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#400 


💡 풀이 사항
📆풀이 일자: 2024.02.28
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- 해당 스킬 트리에서 각 스킬이 선행스킬 목록에 포함되면 StringBuilder에 포함 시킨다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#408 


💡 풀이 사항
📆풀이 일자: 2024.03.11
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 문자열

✍ 풀이 방법
스킬로 hashmap을 만들어서 스킬트리가 현재 사용할 수 있는 스킬보다 더 앞선 스킬 트리면 사용할 수 없도록 한다
정규표현식으로 풀어보려고 했는데 java로는 안써봐서 그냥 문자열로 풀었다

**Comment by skdudddl** [comment]
🔗 문제 링크
https://github.com/Hanbat-Study/algorithm/pull/432

💡 풀이 사항
📆풀이 일자: 2024.03.18
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 지금idx와 이전 idx를 이용했다.
- skill에서 skill_tree에 같은 문자가 있으면 그때의 idx를 curidx로 지정
- curidx가 lastidx+1인지 아닌지 확인해주었다
- 맞으면 answer+1 해줬다
