### ISSUE TITLE
[Level2] [1차] 캐시

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Study/algorithm#409]
🔗 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/17680

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Study/algorithm/pull/427

🔥 메모리:
🔥 시간:

💡 풀이 사항
📆풀이 일자: 2024.03.18
⏰풀이 시간: 240분 00초
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- ArrayList를 활용해서 구현했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
https://github.com/Hanbat-Study/algorithm/pull/428

🔥 메모리:
🔥 시간:

💡 풀이 사항
📆풀이 일자: 2024.03.18
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 처음에 먼저 linkedlist에 캐시사이즈넣고 시작했는데 계속 11,19,20인가? 암튼 계속 틀렸다고 함
- 그래서 반레 찾아봤는데 처음에 넣을 때 같은 것이 있을 수 있다는 걸 알게됨
- 그래서 사이즈가 0일 때랑 아닐 때로 해서 존재하는지 확인하면서 구현

**Comment by GeonHui2** [comment]
🔗 문제 링크
#412 

💡 풀이 사항
📆풀이 일자: 2024.03.10
⏰풀이 시간: 20분 00초
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- queue를 사용해서 queue에 도시가 있다면 해당 도시를 삭제 후 다시 추가해준다.
- 해당 도시가 없고 길이가 작다면 추가 길이가 길다면 삭제 후 추가해주었다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#420 

💡 풀이 사항
📆풀이 일자: 2024.03.15
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- 도시 이름을 전부 소문자로 바꿔 비교
- cache에 도시 이름이 존재하면, 해당 도시를 삭제 후 다시 추가
- 존재하지 않으면, cache의 현재 크기 확인 후 full이 아닐 경우 추가, full일 경우 0번 항목 삭제 후 추가
