### ISSUE TITLE
[Level2] 마법의 엘리베이터

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Study/algorithm#410]
🔗 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/148653

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Study/algorithm/pull/429

🔥 메모리:
🔥 시간:

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 240분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 재귀

✍ 풀이 방법
재귀를 이용해 0층으로 도착하는 10의 배수값과 바로 위층에 도착해 -1 하는 경우와 바로 아래층에 도착해 +1 하는 경우에 대해 최솟값을 구했다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#430 

💡 풀이 사항
📆풀이 일자: 2024.03.05
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 재귀

✍ 풀이 방법
- 10으로 나눈 값의 나머지가 6 이상이거나 5와 같을 시 10으로 나눈 값이 5 이상이면 부족한 값을 더한다.
- 아니면 10으로 나눈 값의 나머지를 빼면서 계산한다.

**Comment by skdudddl** [comment]
🔗 문제 링크
https://github.com/Hanbat-Study/algorithm/pull/431

💡 풀이 사항
📆풀이 일자: 2024.03.18
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법

-  10으로 나눈 나머지가 5이상이면 나머지를 더해주고 4이하이면 나머지를 빼줬다
- 나머지가 5일 때는 몫의 나머지가 5이상인지 4이하인지 따져서 똑같이 구했다

**Comment by jisooolee** [comment]
🔗 문제 링크
#434

💡 풀이 사항
📆풀이 일자: 2024.03.18
⏰풀이 시간: 1시간
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- storey을 10으로 나눠 자리수 별로 마법의 돌 최소 개수를 구한다.
- 10으로 나눈 나머지가 5이상이면 10에서 나머지를 뺀 값을 answer에 더해주고 다음 자리수 값에 1을 더해준다.
- 5 미만이면 나머지를 answer에 더해준다.
- 5이면 몫을 10으로 나눈 값이 5 미만일 경우 나머지를 더해주고, 그 외에는 10에서 나머지를 뺀 값을 answer에 더한 뒤 다음 자리수 값에 1을 더해준다.

**Comment by ramrami-S** [comment]
🔗 문제 링크


💡 풀이 사항
📆풀이 일자: 2024.03.18
⏰풀이 시간: 42분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 재귀

✍ 풀이 방법
재귀
