### ISSUE TITLE
[백엔드] 2주차 과제 - User 생성

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Study/algorithm#415]
## 과제 요구 사항
https://www.notion.so/d8de4ff6293b448a99179493e883d557

**Comment by GeonHui2** [comment]
## 🔗 코드 링크

## 💻 어려웠던 부분이나 궁금했던 부분 있으면 적어주세요 (스터디 때 가능하면 설명해줄게요)

**Comment by ensk26** [comment]
## 🔗 코드 링크

![image](https://github.com/Hanbat-Study/algorithm/assets/70767115/66820f21-9aa2-4521-90c9-c835ee0c712c)

![image](https://github.com/Hanbat-Study/algorithm/assets/70767115/5415141b-1443-43cf-8ba6-05fdab7d9e34)

## 💻 어려웠던 부분이나 궁금했던 부분
- 테이블에 들어가는 네이밍을 스네이크 케이스로 작성해 UnsatisfiedDependencyException이 발생, bean에 담지 못하는 오류가 발생

**Comment by ramrami-S** [comment]
## 제출 기한 ~3/19 12:00 AM  (코멘트까지 달아야 제출 완료)
https://github.com/Hanbat-Study/haram-todo

## 과제 요구 사항
폴더구조
![image](https://github.com/Hanbat-Study/algorithm/assets/157570857/04b8fa65-0d8c-4834-8725-9a4592cff024)

회원가입 성공!
![image](https://github.com/Hanbat-Study/algorithm/assets/157570857/e181c8f7-1be8-4473-931b-fb8f62ae3315)

gender나 hometown -> enum 에 이상한 값 들어가면 오류 발생
![image](https://github.com/Hanbat-Study/algorithm/assets/157570857/a4f2d876-7a0f-4a6a-a8fd-30f5a586b392)
![image](https://github.com/Hanbat-Study/algorithm/assets/157570857/72d531d1-d9f8-4433-9c0a-07bc948b9aeb)

로그인 성공!
<img width="1119" alt="스크린샷 2024-03-18 오후 10 00 40" src="https://github.com/Hanbat-Study/algorithm/assets/157570857/9cae0d06-c196-43f5-a8c2-003d23cfd792">

회원이 아니거나 비밀 번호 틀리면 로그인 실패
<img width="905" alt="스크린샷 2024-03-18 오후 10 02 16" src="https://github.com/Hanbat-Study/algorithm/assets/157570857/e897015d-af5a-44bc-8bd3-8ef8b9e4d3c4">
<img width="731" alt="스크린샷 2024-03-18 오후 10 03 18" src="https://github.com/Hanbat-Study/algorithm/assets/157570857/6e97aacb-fcb5-4424-85c0-99243c2052cf">

## 💻 어려웠던 부분이나 궁금했던 부분 있으면 적어주세요 (스터디 때 가능하면 설명해줄게요)
- enum을 잘 몰랐는데 찾아보니 enum className() {} 이런 식으로 클래스처럼 만들어서 enum 처리 해줄 수 있는 것 같더라구여 하지만 못하겠어서 그냥 if 문으로 처리해 줬는데 enum 클래스?로 구현 하려면 어떻게 해야 하는 지

**Comment by jisooolee** [comment]
🔗 코드 링크
https://github.com/Hanbat-Study/jisu-todo/tree/main/ToDoList
- signup
![image](https://github.com/Hanbat-Study/algorithm/assets/39691728/ee93c7fd-ed3a-441b-9042-ce33a22a9a6f)
![image](https://github.com/Hanbat-Study/algorithm/assets/39691728/05912eea-af5b-46ea-9bde-61c4e9a31240)



- signin
![image](https://github.com/Hanbat-Study/algorithm/assets/39691728/5e24cc5f-cf15-4473-843b-1e9d999c3333)



💻 어려웠던 부분이나 궁금했던 부분 있으면 적어주세요 (스터디 때 가능하면 설명해줄게요)

- 저기 보면 birth를 넣어줬는데 null로 들어가는데 왜 그런지 모르겠어요
- 블로그 서치했을 땐 toEntity를 많이 사용하던데 안 쓰는 게 더 나은 이유 알고 싶어요
- 예외처리하는 로직에 대해 설명해주면 좋겠고 레포지터리에서 findXXX에 대해서도 설명해주세요
